### ISSUE TITLE
Implement global sOTU nicknames

### ISSUE THREAD

**Issue by ababaian** [ababaian/palmdb#1]
Numbers like are difficult to read, like `u1717171` vs `u1777171`. For `palmID` and such I've implemented "Nicknames" for each sOTU which are of the form <adjective><Noun>. 

![image](https://github.com/ababaian/palmdb/assets/9220907/afb53c3d-dcc5-4e00-a829-3d8cf6c1b4db)

In the next release, generate a global `nickname.txt` file retaining the informal nicknames already used, and ~10 million additional nicknames to fix the nicknames for sOTU `u1` ... `u10000000`

**Comment by almosnow** [comment]
https://github.com/ababaian/palmdb/issues/8

(can't close)
