### ISSUE TITLE
Add serratus.io link

### ISSUE THREAD

**Issue by ababaian** [ababaian/palmdb#2]
Link https://serratus.io/palmdb to the the main github page (https://github.com/ababaian/palmdb)

**Comment by lukepereira** [comment]
This is resolved now, feel free to close

**Comment by ababaian** [comment]
not working yet on my machine? Does achange have to be pushed?

**Comment by lukepereira** [comment]
Sorry, i misunderstood. I only updated the existing references to https://github.com/rcedgar/palmdb

Just added a new route for palmdb, though it's not actually referenced anywhere in the app
