### ISSUE TITLE
[palmdb4] Find palm DB sequence files and extract sOTU list

### ISSUE THREAD

**Issue by almosnow** [ababaian/palmdb#4]

**Comment by almosnow** [comment]
![IMG_2649](https://github.com/user-attachments/assets/cd803b03-8191-406f-b5fb-545997dca65c)

**Comment by ababaian** [comment]
See: main README for `palmID` to download. If you don't find the files you need easily please document this and we will update the README / workflow to find the files more easily:

https://github.com/ababaian/palmdb

**Comment by almosnow** [comment]
https://s3.amazonaws.com/palm.db/2023-04-24/final/sotus.palmprint.faa
